openebs/velero-plugin

Makefile
ark-blockstore-cstor/main.go
pkg/cstor/cstor.go
pkg/snapshot/snap.go

Changes:
- Updating import path from `openebs/ark-plugin` to `openebs/velero-plugin`
Signed-off-by: mayank <mayank.patel@cloudbyte.com>

Fix(travis): Updating import path for package openebs/ark-plugin

---

pkg/cstor/cstor.go

This PR fixes #17 
After completion of snapshot restore, velero creates volume from unstructured PV object returned by volumeSnapshotter. Since velero-plugin creates PVC and PV to restore a snapshot, this unstructured PV should have the same name as newly created PV's Name.
During restore, the plugin should update the volume details according to the newly created volume.

Fixing restore for multiple volumes

---

README.md
example/06-volumesnapshotlocation.yaml
pkg/clouduploader/conn.go
pkg/clouduploader/operation.go

Changes:
- In current implementation, we are using `prefix` from `VolumeSnapshotLocation` for bcakup file name. In `BackupStorageLocation`,  `prefix` is used for backup path. This PR fix this issue.
With this change, `prefix` from `VolumeSnapshotLocation` will be used for backup path only.
So, if user has configured `VolumeSnapshotLocation` with `prefix:testcluster` then backup files will be stored in `bucket_name/testcluster/backups/backup_name`.

Fix(VolumeSnapshotLocation, prefix): using prefix for backup path instead of file name

---

README.md
example/06-volumesnapshotlocation.yaml
pkg/clouduploader/conn.go
pkg/clouduploader/operation.go

Cherry-pick for https://github.com/openebs/velero-plugin/pull/25

Fix(cherry-pick, VolumeSnapshotLocation): using prefix for backup path instead of file name

---

pkg/clouduploader/conn.go
pkg/cstor/cstor.go

Changes:
- Whenever `velero-plugin` receives a snapshot request, it will check(using label `openebs.io/cas-type:cstor`) if PV is CStor PV or not.
- If PV is having CStor label(`openebs.io/cas-type:cstor`) then `velero-plugin` will execute the snapshot action
- If PV doesn't have the CStor label then `velero-plugin` will not execute the snapshot action.
-  Code refactoring 
- Using var `ok` instead of var `err` to check error on fetching key from map.
- Changed `casType` to `casTypeCStor` for `cstor`.
This PR fixes https://github.com/openebs/velero-plugin/issues/27

Fix(VolumeID) : adding a check for CStor Volume during backup

---

pkg/cstor/cstor.go

Fix(VolumeInfo) : skip backup silently if volume is not supported by `velero-plugin`

---

pkg/cstor/cstor.go

Fix(cherry-pick, VolumeInfo) : skip backup silently if volume is not supported by `velero-plugin`

---

README.md

Changes:
- Updating compatibility matrix for `1.1.0` release
- Adding more information on `prefix` and `backupPathPrefix` parameter of `volumesnapshotlocation`

doc(readme): updating readme with latest release

---

pkg/cstor/cstor.go

Changes:
- Fixing spelling mistake in `pkg/cstor/cstor.go`.
- `sufficient` spelled as `sufficent`.

fix(travis, misspell) : fixing spelling mistake

---

README.md
example/06-volumesnapshotlocation.yaml
pkg/cstor/cstor.go
pkg/snapshot/snap.go

Changes:
velero-plugin assumes that openebs is installed in namespace `openebs`.
If openebs is installed in different namespace then user can configure
this parameter to execute backup operation.
sample volumesnapshotlocation.yaml:
```
spec:
config:
bucket: test_bucket
namespace: ns1
provider: gcp
provider: openebs.io/cstor-blockstore
```

feat(config): adding support for new parameter `namespace` in volumesnapshotlocation

---

script/install-velero.sh
tests/openebs/logs.go
tests/openebs/storage_install.go
tests/openebs/storage_status.go
tests/sanity/backup_test.go

Changes:
- Adding a check for healthy CVR before triggering a backup.
In the current version, we check for healthy CVR during setup only.
There might be some chances of cstor pod restart and CVR
becomes degraded when we trigger the backup.

fix(ci): adding check for healthy CVR

---

.travis.yml

Changes:
- setting default release values for openebs and openebs/velero-plugin if base branch/tag is other than `x.x.x-XX-velero_x.x.x`.

fix(travis): fixing travis build

---

pkg/cstor/pvc_operation.go

Changes:
- STS uses StorageClass from PVC Annotation or PVC Spec. This PR checks for PVC's annotation for the StorageClass.

fix(statefuleset): update storageclass from PVC annotation

---

example/06-volumesnapshotlocation.yaml
pkg/clouduploader/conn.go
pkg/clouduploader/operation.go
pkg/cstor/cstor.go

Changes: 
- Added support for multiPartChunkSize for remote storage services like s3/minio.
By default value of `multiPartChunkSize` is minimum 5MB and it will be adjusted by the plugin according to volume size unless explicitly set in `volumesnapshotlocations`.
For S3 base storage, Velero-plugin uses multipart upload for snapshot backup. `multiPartChunkSize` for the part upload will be minimum 5 MB. https://docs.aws.amazon.com/AmazonS3/latest/dev/mpuoverview.html
https://docs.aws.amazon.com/AmazonS3/latest/dev/qfacts.html
This value can be increased to avoid performance degradation in case of large number of parts(>500). https://github.com/minio/minio/issues/7206
To configure `VolumeSnapshotLocations` with `multiPartChunkSize`:
```
spec:
config:
bucket: velero
multiPartChunkSize: 10Mi …
```

feat(s3, partSize) :  support for multiPartChunkSize

---

README.md
example/06-volumesnapshotlocation.yaml
pkg/clouduploader/conn.go
pkg/clouduploader/operation.go
pkg/cstor/api_service.go
pkg/cstor/cstor.go
pkg/cstor/status.go
tests/k8s/log.go
tests/openebs/storage_status.go
tests/sanity/backup_test.go

Changes:
- This PR adds support to cleanup backup resources generated by maya-apiserver, to execute backup of CStor volumes.
Velero-plugin will execute clean-up operation in following scenarios:
- In case of normal backup, Plugin will send delete request to api-server once the backup for the cstor volume completes
- In case of scheduled backup, Plugin will send delete request, for second-last completed backup, to api-server.
- If backup, normal or scheduled,  is failed then plugin will send the delete request to api-server.
- In case of scheduled backup, 
A) If backup is last generated one then Maya-Apiserver will delete the relevant CStorBackup, CStorCompletedBackups and CStor snapshot, so next new backup will be full backup
B) If backup is not the last one then maya-apiserver will …

 feat(cstorBackup, delete): support for snapshot deletion

---

.travis.yml

velero-plugin will be using the tag format same as `openebs/maya`. Due to that we need to update the travis file which was using the old format `1.3.0-RC1-velero_1.0.0`. 
As of now velero-plugin BDD is using golang code for testing instead of velero binaries. For testing code we are using velero code base v1.0.0 only. Testing multiple version is not feasible since it requires multiple copies of the testing code, so we will continue BDD with v1.0.0 until we update the testing code to use v1.3.0.

chore(travis): updating travis file according to new release format

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/pull_request_template.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
GOVERNANCE.md
MAINTAINERS
README.md
RELEASE.md
code-standard.md
developer-setup.md

Changes:
- This PR adds project specific files to guide contributors and repo owner/maintainer
List of the files is as below:
-  [github issue template](https://github.com/openebs/velero-plugin/blob/8bfe6e241899e609d8672bfa4e4170ad731c053c/.github/ISSUE_TEMPLATE/bug_report.md)
-  [github feature request template](https://github.com/openebs/velero-plugin/blob/8bfe6e241899e609d8672bfa4e4170ad731c053c/.github/ISSUE_TEMPLATE/feature-request.md)
- [git hub pull request template](https://github.com/openebs/velero-plugin/blob/8bfe6e241899e609d8672bfa4e4170ad731c053c/.github/pull_request_template.md)
- [CODE_OF_CONDUCT.md](https://github.com/openebs/velero-plugin/blob/8bfe6e241899e609d8672bfa4e4170ad731c053c/CODE_OF_CONDUCT.md)
- [CONTRIBUTING.md](https://github.com/openebs/velero-plugin/blob/8bfe …

docs(project): adding project specific files

---

.travis.yml
README.md
changelogs/unreleased/72-mynktl
pkg/clouduploader/operation.go
pkg/clouduploader/server.go
pkg/clouduploader/server_utils.go
pkg/cstor/cstor.go
pkg/cstor/pv_operation.go
pkg/cstor/pvc_operation.go
pkg/cstor/status.go
pkg/velero/restore.go
pkg/velero/sort.go
pkg/velero/velero.go
tests/openebs/logs.go
tests/openebs/storage_install.go
tests/sanity/backup_test.go
tests/velero/logs.go
tests/velero/restore.go

Changes:
- Enabling remote restore in different namespace.
When restore, for cstor volume, is performed for remote-backup then velero-plugin find the velero relevant restore resource and get the namespace mapping and creates a pvc in that namespace.
plugin find the relevant restore from the sorted list(creationTimestamp in decreasing order) of restore resource using following criteria:
- restore is in in-progress state **AND** backup for that restore matches with the backup name from snapshotID
fixes: https://github.com/openebs/velero-plugin/issues/67

feat(remote-restore): enabling restore in different namespace

---

.travis.yml
Makefile
pkg/clouduploader/server.go
pkg/clouduploader/server_utils.go
pkg/cstor/pv_operation.go
pkg/velero/restore.go
pkg/velero/sort.go
pkg/velero/velero.go
velero-blockstore-cstor/main.go

Changes:
- Added new target `check-license` in Makefile to verify copyright messages in files
- Added a build-check in Travis for missing copyright messages.
- Added missing copyright message to the files
fixes: https://github.com/openebs/velero-plugin/issues/74

chore(build): check for missing copyright messages

---

changelogs/unreleased/76-mynktl
example/06-volumesnapshotlocation.yaml
pkg/clouduploader/conn.go

Changes:
- Added support for multiple s3 profiles for volumesnapshotlocation.
- Removed call to get secret file using `AWS_SHARED_CREDENTIALS_FILE` since it is handled by sdk itself
fixes: https://github.com/openebs/velero-plugin/issues/58
Changes were tested locally using multiple s3 profile. Scenarios tested:
- Having two profile, default and prof1 and no profile in VSL
- backup/restore passed
- Having two profile, prof1 and prof2 -- VSL configured with profile `prof1`
- backup/restore passed
- Having two profile, prof1 and prof2 -- no profile in VSL
- backup/restore failed
- Having two profile, default and prof2 -- VSL configured with profile `prof1`
- backup/restore failed

feat(multiple-s3): support for multiple s3 profile

---

changelogs/unreleased/79-mynktl
pkg/cstor/cstor.go

This PR is fix for [bug](https://github.com/openebs/velero-plugin/issues/78) 
This PR add a check in delete snapshot API of plugin to verify if `snapshotID` is empty or not.
This PR also add additional check for `snapshotID` verification in `getInfoFromSnapshotID`, used for getting information about volume and backup name.
No.
- deletion of failed backup with empty snapshotID
- deletion completes with warning message
```
time="2020-05-07T07:59:52Z" level=warning msg="Empty snapshotID" backup=b5 cmd=/plugins/velero-blockstore-cstor …
```

fix(snapshotID): empty check for snapshotID

---

Dockerfile
Makefile
push

There are cases where users might want to build and push
container images in their own environments.
This commit will help customizing docker images via environment variables:
- The following ENV help specify custom docker build args
- DBUILD_SITE_URL ( default: https://openebs.io )
- DBUILD_REPO_URL ( default: https://github.com/openebs/node-disk-manager )
- The following ENV allows Travis to specify custom image org
- IMAGE_ORG (default: openebs )
- The following ENV will allow specifying an extra tag suffix
- TAG_SUFFIX ( default: none )
No. 
**If the changes in this PR are manually verified, list down the scenarios covered:**:
Used make file commands to create …

refact(build): make the docker images configurable

---

push

This PR removes the leading `v` from image tags. This is required to make the image name
consistent with other openebs images 
- remove the leading `v` prefix from image tag
No
**If the changes in this PR are manually verified, list down the scenarios covered:**:
**Any additional information for your reviewer?** : 
**Checklist:**

refactor(build): trim leading v from image tag

---

changelogs/unreleased/85-mynktl
pkg/cstor/pvc_operation.go

This PR is fix for https://github.com/openebs/velero-plugin/issues/84 and https://github.com/openebs/maya/issues/1689
This PR clears the annotation `openebs.io/created-through` from restore cstor PVC.
**Does this PR require any upgrade changes?**: No
Following scenario verified
- Created remote backup of percona application, using cstor volume in namespace `test`, through velero-plugin
- Created restore from that backup in different namespace `ns1`
- Verified that PVC doesn't have annotation `openebs.io/created-through`
- Created restic backup for the restored percona application
- …

fix(restore): removing annotation openebs.io/created-through from PVC

---

changelogs/unreleased/85-mynktl
pkg/cstor/pvc_operation.go

This PR is fix for https://github.com/openebs/velero-plugin/issues/84 and https://github.com/openebs/maya/issues/1689
This PR clears the annotation `openebs.io/created-through` from restore cstor PVC.
Cherry-pick of https://github.com/openebs/velero-plugin/pull/85
**Does this PR require any upgrade changes?**: No
Following scenario verified
- Created remote backup of percona application, using cstor volume in namespace `test`, through velero-plugin
- Created restore from that backup in different namespace `ns1`
- Verified that PVC doesn't have annotation `openebs.io/created-through`
- …

cherr-pick(fix,restore): removing annotation openebs.io/created-through from PVC

---

.golangci.yml
Makefile

Changes:
- Enable only few linters for travis build and local build
- List of enabled linters
- deadcode
- goconst
- gofmt
- goimports
- gosec
- scopelint
- unparam
- unused 

chore(linters): enabling few linters for local and travis build

---

changelogs/unreleased/108-mittachaitu
pkg/cstor/api_service.go
pkg/cstor/cstor.go
pkg/cstor/pv_operation.go

Please, go through these steps before you submit a PR. ## Remove this line
This PR required to support local restore of cStor CSI volume.
This PR handles the response of restore request and populate the spec required for CStor CSI volume.
No
- Backup the CSI volume and restored it in a different namespace.
- Backup the Non-CSI volume and restored it in a different namespace.
**Checklist:**

fix(csi, local restore): add support for local restore of cStor CSI volume

---

changelogs/116-pawanpraka1
go.mod
velero-blockstore-openebs/main.go

Running the Velero deployment with Log level as Debug is not printing any debug log that plugin has.
**What this PR does**
Velero provides a logger that can be used by plugins to log structured
information to the main Velero server log or per-backup/restore logs.
It also passes a --log-level flag to each plugin binary, whose value
is the value of the same flag from the main Velero process.
This means that if you turn on debug logging for the Velero server via
--log-level=debug, plugins will also emit debug-level logs.
**Checklist:**

feat(log): making log level available for velero plugin

---

changelogs/unreleased/118-pawanpraka1
pkg/velero/restore.go
pkg/zfs/plugin/restore.go
pkg/zfs/plugin/zfs.go

fixes : https://github.com/openebs/zfs-localpv/issues/200
We have the node affinity set on the PV and the ZFSVolume object
which has the original node name. While doing the restore if original
nodes are not present, the Pod will not come into running state.
Doc: https://velero.io/docs/v1.4/restore-reference/#changing-pvc-selected-node.
Here we can create a config map which will have the node mapping like below:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: change-pvc-node-selector-config
namespace: velero
labels:
velero.io/plugin-config: ""
velero.io/change-pvc-node: RestoreItemAction
data:
pawan-old-node1: pawan-new-node1
pawan-old-node2: pawan-new-node2
``` …

feat(zfspv): adding support to restore on different setup/nodes

---

changelogs/unreleased/115-mynktl
example/06-volumesnapshotlocation.yaml
pkg/clouduploader/conn.go

Fixes: https://github.com/openebs/velero-plugin/issues/113
This PR add support to pass custom certificate for s3 base object storage. PR also includes changes to disable certificate verification for s3 object storage.
With this PR, following additional fields can be configured in volumesnapshotlocation for s3 base storage:
- caCert
Base64 encoded certificate data.
- insecureSkipTLSVerify
Default value is "false". 
No.
- MinIO cofigured with custom certificate
- volumesnapshotlocation configured with caCert
- backup/restore passed
- …

feat(s3): support to use custom certificate for s3 object storage

---

changelogs/unreleased/121-pawanpraka1
pkg/clouduploader/operation.go
pkg/zfs/plugin/backup.go
pkg/zfs/plugin/restore.go
pkg/zfs/plugin/zfs.go
pkg/zfs/utils/utils.go

fixes: https://github.com/openebs/zfs-localpv/issues/199
Adding incremental backup and restore support for ZFS-LocalPV. 
We can create the snapshot location as below
```yaml
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
name: incr
namespace: velero
spec:
provider: openebs.io/zfspv-blockstore
config:
bucket: velero
prefix: zfs
incrBackupCount: "3" # number of incremental backup we want to have
namespace: openebs # this is namespace where ZFS-LocalPV creates all the CRs, passed as OPENEBS_NAMESPACE env in the ZFS-LocalPV deployment
provider: aws
region: minio
s3ForcePathStyle: "true"
s3Url: http://minio.velero.svc:9000
```
here we can specify how many …

feat(zfspv): adding support to do incremental backup/restore

---

changelogs/unreleased/121-pawanpraka1
pkg/clouduploader/operation.go
pkg/zfs/plugin/backup.go
pkg/zfs/plugin/restore.go
pkg/zfs/plugin/zfs.go
pkg/zfs/utils/utils.go

We can create the snapshot location as below
```yaml
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
name: incr
namespace: velero
spec:
provider: openebs.io/zfspv-blockstore
config:
bucket: velero
prefix: zfs
incrBackupCount: "3" # number of incremental backup we want to have
namespace: openebs # this is namespace where ZFS-LocalPV creates all the CRs, passed as OPENEBS_NAMESPACE env in the ZFS-LocalPV deployment
provider: aws
region: minio
s3ForcePathStyle: "true"
s3Url: http://minio.velero.svc:9000
```
here we can specify how many incremental backups we want to have. We will create a full backup first and if we have provided non zero value for `incrBackupCount` option, then the plugin will create that many incremental backup. Thing to note here is `incrBackupCount` …

feat(zfspv): adding support to do incremental backup/restore (#121)

---

changelogs/unreleased/124-pawanpraka1
pkg/clouduploader/operation.go
pkg/zfs/plugin/backup.go
pkg/zfs/plugin/restore.go
pkg/zfs/utils/utils.go

User can create a backup using same name (or format) as scheduled backup, this
will cause restore to break as it simply does the lookup based on scheduled name.
There is no difference in the way we take the full backup and scheduled incremental
backup.
Here, we are adding schedule name in the backup file name so that we can list based on
that while doing the restore. The user created backup using schedule name will not be
considered as it is not the scheduled backup so it will not be considered while doing restore.

feat(zfspv): use schedule name to identify the scheduled backup

---

changelogs/unreleased/124-pawanpraka1
pkg/clouduploader/operation.go
pkg/zfs/plugin/backup.go
pkg/zfs/plugin/restore.go
pkg/zfs/utils/utils.go

cherry-Pick : https://github.com/openebs/velero-plugin/pull/124
User can create a backup using same name (or format) as scheduled backup, this
will cause restore to break as it simply does the lookup based on scheduled name.
There is no difference in the way we take the full backup and scheduled incremental
backup.
Here, we are adding schedule name in the backup file name so that we can list based on
that while doing the restore. The user created backup using schedule name will not be
considered as it is not the scheduled backup so it will not be considered while doing restore.

feat(zfspv): use schedule name to identify the scheduled backup (#124)

---

changelogs/unreleased/128-pawanpraka1
pkg/zfs/plugin/backup.go
pkg/zfs/utils/utils.go

We use pvname and snapname for creating the backup. Now since we are returning schedule
name also in snapshotID, so While deleting the ZFSBackup CR we should use the pvname and snapname.
We broke this in https://github.com/openebs/velero-plugin/pull/125.
Also fixed the backup compatibility for older backups where we were not fetching the schedule name.
We should fetch the schedule name from the backup name using the naming format.

fix(zfspv): fixing the backup deletion for ZFS-LocalPV

---

changelogs/unreleased/128-pawanpraka1
pkg/zfs/plugin/backup.go
pkg/zfs/utils/utils.go

Cherry-pick : https://github.com/openebs/velero-plugin/pull/128
We use pvname and snapname for creating the backup. Now since we are returning schedule
name also in snapshotID, so While deleting the ZFSBackup CR we should use the pvname and snapname.
We broke this in https://github.com/openebs/velero-plugin/pull/125.
Also fixed the backup compatibility for older backups where we were not fetching the schedule name.
We should fetch the schedule name from the backup name using the naming format.

fix(zfspv): fixing the backup deletion

---

.travis.yml
Makefile.buildx.mk
changelogs/unreleased/133-prateek

Signed-off-by: prateekpandey14 <prateek.pandey@mayadata.io>
Enabling more than two arch in the multi-arch builds is resulting in increased build times as well as
intermittent failures in running the builds.
Limiting to two archs - amd64 and arm64 for now.

refact(builds): run only amd64 and arm64 multi arch builds

---

script/install-velero.sh

Changes:
- Updating travis test setup to use `openebs/velero-plugin-amd64:ci` image instead of `openebs/velero-plugin:ci`. Ref: https://github.com/openebs/velero-plugin/pull/132

fix(travis): Travis test setup to use correct velero-plugin image

---

README.md
changelogs/unreleased/131-zlymeda
example/06-volumesnapshotlocation.yaml
pkg/cstor/cstor.go
pkg/cstor/cvr_operation.go
pkg/cstor/pvc_operation.go
pkg/snapshot/snap.go
script/minio.yaml
script/volumesnapshotlocation.yaml
tests/app/application_setup.go
tests/k8s/status.go
tests/openebs/storage_install.go
tests/sanity/backup_test.go
tests/velero/backup.go
tests/velero/restore.go
tests/velero/schedule.go

Marking CVRs after successful restore with openebs.io/restore-completed if autoSetTargetIP=true or restoreAllIncrementalSnapshots=true
Currently users have to set targetip on CVRs after restore. This PR automates setting targetip.
If corresponding VolumeSnapshotLocation has autoSetTargetIP=true or restoreAllIncrementalSnapshots=true then CVRs are marked with annotation openebs.io/restore-completed which is then handled in https://github.com/openebs/maya/pull/1761 or https://github.com/openebs/cstor-operators/pull/198
No
I ran `make test` …

fix(restore): mark CVRs after restore is completed

---

changelogs/unreleased/139-pawanpraka1
pkg/velero/restore.go

Velero has updated the label selector for change-pvc Restore action item(https://github.com/vmware-tanzu/velero/pull/2970).
Updating the velero plugin for ZFS-LocalPV with the same label.
**Checklist:**

fix(restore): updating the label selector for restore

---

changelogs/unreleased/144-mynktl
pkg/cstor/cvr_operation.go

This PR fixes https://github.com/openebs/velero-plugin/issues/141
During restore, we are annotating CVRs for restore completion and wait till CVR become healthy. Ref. https://github.com/openebs/velero-plugin/pull/131. If application is deployed using `[target affinity policy](https://docs.openebs.io/v090/docs/next/configuresc.html#Target-Affinity-Policy)` then restore, using `autoSetTargetip`, was not able to complete. This happens because CVRs will turn to healthy when the target pod gets scheduled. In case of target-affinity, target-pod gets scheduled only after application pod. This PR removes this checks of healthy CVR.
No
**If the changes in this PR are …

fix(targetip): Removing wait on setting target ip for CVR

---

changelogs/unreleased/147-pawanpraka1
go.mod
go.sum
pkg/zfs/plugin/restore.go

fixes: https://github.com/openebs/zfs-localpv/issues/286
Encrypted pool does not allow the volume to be pre created for the
restore purpose.
Here changing the design to do the restore first
and then create the ZFSVolume object which will bind the volume
already created while doing restore.
Backward compatibility is maintained by ZFS-LocalPV.
**Depends On**
https://github.com/openebs/zfs-localpv/pull/292

fix(restore): adding support to restore in an encrypted pool for ZFS-LocalPV

---

changelogs/unreleased/154-mynktl
example/06-local-volumesnapshotlocation.yaml
example/06-volumesnapshotlocation.yaml
pkg/cstor/api_service.go
pkg/cstor/cstor.go

Fixes https://github.com/openebs/velero-plugin/issues/148
This PR adds a new VolumeSnapshotLocation config parameter `restApiTimeout` to configure the timeout for HTTP REST requests between plugin and cstor services.
No
yes. testing logs
```
time="2021-04-30T12:36:30Z" level=info msg="Initializing velero plugin for CStor" backup=velero/b1 cmd=/plugins/velero-blockstore-openebs logSource="/home/mayank/go/src/github.com/openebs/velero-plugin/pkg/snapshot/snap.go:36" pluginName=velero-blockstore-openebs
time="2021-04-30T12:36:30Z" level=info …
```

fix(timeout): Adding new VSL parameter to set timeout for HTTP request

---

pkg/velero/velero.go
pkg/zfs/plugin/zfs.go

Signed-off-by: Rahul Grover <rahulgrover99@gmail.com>
Improves code quality. Removes `S1005` (Drop unnecessary use of the blank identifier) and `opt.semgrep.err-nil-check`
It removes superfluous nil err check before return and unnecessary assignment to the blank identifier.
No
NA
NA

(bugbash) style(zfspv): Removing redundant pieces of code

---

pkg/zfs/plugin/restore.go

Signed-off-by: Sonia Singla <soniasingla.1812@gmail.com>
Replace `for true{}`  with `for{}`

Replace for true{}  with for{}
