openebs/velero-plugin

- review/ark-blockstore-cstor/cloud.go
- review/ark-blockstore-cstor/cstor.go
- review/ark-blockstore-cstor/main.go
- review/ark-blockstore-cstor/server.go
- review/ark-blockstore-cstor/snap.go
Changes:
- Ark-plugin to backup/restore cstor volume.
- Please go through this [Design document](https://docs.google.com/document/d/1-4WsM0AjLORb3lTCUUGyYOY_LNdTOATFesi7kTAr7SA/edit?usp=sharing) for a detailed explanation of the code.
> Ark-plugin code

- Gopkg.lock
- Gopkg.toml
- README.md
- example/06-volumesnapshotlocation.yaml
- pkg/clouduploader/conn.go
- pkg/clouduploader/operation.go
- velero-blockstore-cstor/main.go
- vendor/github.com/heptio/velero/site/_includes/contributors.html
Changes:
- Adding support for MinIO object store
- Updating example files
- Updating velero version to `v1.0.0`
> feat(volumesnapshotlocation): support for MinIO object store

- README.md
Changes:
- fixing velero doc link
- adding `openebs:1.0.0` to support matrix
> doc(readme) : Updating support matrix with openebs 1.0.0 release

- pkg/cstor/cstor.go
This PR fix https://github.com/openebs/velero-plugin/issues/20.
> Fix(apiservice): using label to fetch Maya-Apiserver Service

- pkg/cstor/cstor.go
Cherry-pick for PR https://github.com/openebs/velero-plugin/pull/21
> Fix(cherry-pick, apiservice): using label to fetch Maya-Apiserver Service

- pkg/clouduploader/conn.go
- pkg/cstor/cstor.go
Cherry-pick for https://github.com/openebs/velero-plugin/pull/28
> Fix(cherry-pick, VolumeInfo) : adding a check for CStor Volume during backup

- README.md
Changes:
- Added TOC for the readme
- Changed the sequence of section according to usability
> doc(readme): adding TOC and refactoring the content

- pkg/cstor/pvc_operation.go
> cherry-pick(fix, statefuleset): update storageclass from PVC annotation

- .travis.yml
- Makefile
- add arm64 builds
- tests are configured to be executed only on amd64
Signed-off-by: Akhil Mohan <akhil.mohan@mayadata.io>
> feat(build): add arm64 builds

- .travis.yml
- Makefile
- add arm64 builds
- tests are configured to be executed only on amd64
Signed-off-by: Akhil Mohan <akhil.mohan@mayadata.io>
cherry-pick #61
> cherry-pick(build): add arm64 builds (#61)

- Dockerfile
fixes: https://github.com/openebs/openebs/issues/2991
> chore(build): upgrade the apline image version for velero-plugin to 3.10.4

- CHANGELOG.md
> chore(doc): adding change-log for 1.9.0

- README.md
> chore(readme): updating README.md for 1.9.0

- README.md
Changes:
- Adding an additional step/information about namespace existence/creation for remote restore
> docs(readme): updating readme with namespace creation

- Makefile
- go.mod
- go.sum
- pkg/snapshot/snap.go
Changes:
- Removing heptio package from pkg/snapshot import path
- Updating makefile to verify go mod files
> refactor(gomod): removing heptio package

- pkg/cstor/api_service.go
- pkg/cstor/cstor.go
- pkg/cstor/status.go
This PR fixes #83 
This PR adds support to backup/restore cstor v1 volumes
No
TBD
**Pending**
- status verification for CVC backup rest call 
**Checklist:**
Signed-off-by: mynktl <mayank.patel@mayadata.io>
> feat(cstorv1): backup/restore for cstor v1

- pkg/cstor/api_service.go
Please, go through these steps before you submit a PR. ## Remove this line
**Checklist:**
> chore(log): logging response message from REST call

- README.md
Please, go through these steps before you submit a PR. ## Remove this line
**Checklist:**
> chore(readme): updating version compatibility matrix

- CHANGELOG.md
This PR add changelog for v1.12.0
**Checklist:**
>  docs(changelog): Adding changelog for v1.12.0

- Makefile
> chore(linters): disabling deadcode,scopelint,unused linter for travis/local build

- changelogs/unreleased/108-mittachaitu
- pkg/cstor/api_service.go
- pkg/cstor/cstor.go
- pkg/cstor/pv_operation.go
Signed-off-by: mittachaitu <sai.chaithanya@mayadata.io>
Please, go through these steps before you submit a PR. ## Remove this line
This PR is cherry-pick of #108 
No
**Checklist:**
> cherrypick(fix, csi local restore): add support for local restore of cStor CSI volume

- .github/workflows/build.yml
- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- Dockerfile
- Makefile
- Makefile.buildx.mk
- plugin.Dockerfile
- script/buildxpush.sh
Signed-off-by: shubham <shubham.bajpai@mayadata.io>
This PR adds support for building multi-arch builds using github actions.
No
**Checklist:**
> chore(build): add support for multiarch build

- .github/workflows/build.yml
- .github/workflows/release.yml
Signed-off-by: Akhil Mohan <akhil.mohan@mayadata.io>
- replace deprecated methods from github actions workflows.
No
**Checklist:**
> chore(actions): replace deprecated methods in github actions

- CHANGELOG.md
> chore(CHANGELOG): add changelogs for v2.8.0

- pkg/cstor/pvc_operation.go
Signed-off-by: Sonia Singla <soniasingla.1812@gmail.com>
Remove dead functions
> Remove dead functions

- pkg/cstor/cvr_operation.go
Signed-off-by: Sonia Singla <soniasingla.1812@gmail.com>
This PR removes dead code and clean up the file!!
> Remove dead code and clean up the file

- pkg/zfs/plugin/restore.go
Signed-off-by: Sonia Singla <soniasingla.1812@gmail.com>
Dead functions removed
> Dead functions removed

- .github/workflows/build.yml
- .github/workflows/pull_request.yml
- script/install-velero.sh
- update Kubernetes version to v1.20.1 in GitHub workflow
- update Velero version to v1.6.0 in GitHub workflow
**Checklist:**
> chore(workflow): updating k8s and Velero version

- .github/workflows/build.yml
- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- GOVERNANCE.md
- README.md
- RELEASE.md
- code-standard.md
- developer-setup.md
- pkg/cstor/cstor.go
- updating branch reference from master to develop in following files:
- .github/workflows/build.yml
- .github/workflows/pull_request.yml
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- GOVERNANCE.md
- README.md
- RELEASE.md
- code-standard.md
- developer-setup.md
- pkg/cstor/cstor.go
**Checklist:**
> chore(build,doc): updating default branch to develop
